server:
  port: 8080

file:
  upload-dir: D:/upload/videos
  processed-dir: D:/processed/videos

whisper:
  url: http://localhost:9000/transcribe

caption:
  url: http://localhost:9001/caption


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/book?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 800MB
      max-request-size: 800MB

  mvc:
    static-path-pattern: /photo/**
  web:
    resources:
      static-locations: file:///D:/static/

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: it.pojo
  configuration:
    map-underscore-to-camel-case: true